#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 20-discourse
#prepare_service
SERVICE_NAME="rails"

check_container_initialized


if var_true "${DELIVER_SECURE_ASSETS}" ; then export DISCOURSE_FORCE_HTTPS=true ; fi
export DISCOURSE_SITE_TITLE=${SITE_TITLE}
export UNICORN_WORKERS=${UNICORN_WORKERS}

liftoff
if [ -f /app/bin/unicorn ] && [ -f /app/config/unicorn.conf.rb ]; then
  app_server_cmd=bin/unicorn
  app_server_conf=config/unicorn.conf.rb
  print_start "Starting Unicorn - Discourse $(grep -o "ADD: Discourse .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $3}')"
else
  app_server_cmd=bin/pitchfork
  app_server_conf=config/pitchfork.conf.rb
  print_start "Starting Discourse $(grep -o "ADD: Discourse .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $3}')"
fi

cd /app/
exec sudo -Eu "${DISCOURSE_USER}" RUN_PITCHFORK=0 \
                                ${app_server_cmd} \
                                  -E production \
                                  -o 0.0.0.0 \
                                  -p "${LISTEN_PORT}" \
                                  -c "${app_server_conf}" ${UNICORN_ADDITIONAL_ARGS}

