#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 20-discourse
#prepare_service
SERVICE_NAME="rails"

check_container_initialized

if [ -f /app/bin/unicorn ] && [ -f /app/config/unicorn.conf.rb ]; then
    app_cmd=unicorn
    export UNICORN_WORKERS=${UNICORN_WORKERS}
    app_args=${UNICORN_ADDITIONAL_ARGS}
else
    app_cmd=pitchfork
    app_args=${PITCHFORK_ADDITIONAL_ARGS}
fi

if var_true "${DELIVER_SECURE_ASSETS}" ; then export DISCOURSE_FORCE_HTTPS=true ; fi
export DISCOURSE_SITE_TITLE=${SITE_TITLE}

liftoff

print_start "Starting Discourse (${app_cmd} $(grep -o "ADD: Discourse .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $3}'))"
cd /app/
exec sudo -Eu "${DISCOURSE_USER}" RUN_PITCHFORK=0 \
                                /app/bin/${app_cmd} \
                                  -E production \
                                  -o 0.0.0.0 \
                                  -p "${LISTEN_PORT}" \
                                  -c /app/config/${app_cmd}.conf.rb ${app_args}
