#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="discourse"

cat <<EOF

*************************************************************************************************
*                                                                                               *
*                    END OF LIFE NOTICE OCTOBER 09, 2025                                        *
*                               tiredofit/discourse                                             *
*                                                                                               *
* This image is no longer maintained as of and will not receive updates.                        *
*                                                                                               *
* A successor image is available at:                                                            *
*                                                                                               *
* Repository | Documentation:                                                                   *
*   - https://github.com/nfrastack/container-discourse                                          *
*                                                                                               *
* Image Registries:                                                                             *
*   - https://hub.docker.com/r/nfrastack/discourse                                              *
*   - https://github.com/nfrastack/container-moodle/pkgs/container/container-discourse          *
*                                                                                               *
* Please visit https://nfrastack.com for more information.                                      *
*                                                                                               *
*************************************************************************************************

EOF

sleep 15


bootstrap_filesystem
configure_discourse
custom_files /app/
custom_scripts
configure_plugins
setup_shell
migrate_db
compile_assets
create_admin_user
chown discourse:discourse /app

liftoff
