#!/command/with-contenv bash

source /container/base/functions/container/init
source /container/functions/20-discourse
prepare_service
PROCESS_NAME="rails"

check_container_initialized
liftoff

if var_true "${DELIVER_SECURE_ASSETS}" ; then export DISCOURSE_FORCE_HTTPS=true ; fi
export DISCOURSE_SITE_TITLE=${SITE_TITLE}
export UNICORN_WORKERS=${UNICORN_WORKERS}

cd /app/
print_start "Starting Unicorn - Discourse version ${DISCOURSE_VERSION}"
exec s6-setuidgid discourse \
                    bin/unicorn \
                                    -E production \
                                    -o 0.0.0.0 \
                                    -p "${LISTEN_PORT}" \
                                    -c "config/unicorn.conf.rb" ${UNICORN_ADDITIONAL_ARGS}


