#!/command/with-contenv bash

source /container/base/functions/container/init
source /container/defaults/20-discourse
source /container/functions/20-discourse
prepare_service
PROCESS_NAME="sidekiq"

check_container_initialized
check_service_initialized 20-discourse
liftoff

print_start "Starting Sidekiq"
cd /app/
exec sudo -Eu discourse \
                            bundle exec sidekiq \
                                --concurrency ${SIDEKIQ_THREADS} \
                                --environment production \
                                ${SIDEKIQ_ADDITIONAL_ARGS} >> "${LOG_PATH}"/"${SIDEKIQ_LOG_FILE}" 2>&1
